require("bobby.plugins-setup")
require("bobby.core.options")
require("bobby.core.keymaps")
require("bobby.core.colorscheme")
require("bobby.plugins.nvim-tree")
require("bobby.plugins.comment")  
require("bobby.plugins.lualine")
require("bobby.plugins.telescope")
